scoring:
    rubrics:
        - description: Salary level relative to your floor
          id: salary
          kind: system
          weight: 5
        - description: Remote / hybrid / onsite match
          id: work_arrangement
          kind: system
          weight: 5
        - description: Preferred location match
          id: location
          kind: system
          weight: 5
        - description: Uses preferred technologies
          id: preferred_tech
          items:
            - Java
            - Ruby
          kind: dynamic
          weight: 5
        - description: Avoids technologies you don't want
          id: avoided_tech
          items:
            - Scala
          kind: dynamic
          weight: 5
profile:
    avoided_tech:
        - Scala
    locations:
        - Seattle
    min_salary: 80000
    min_salary_currency: USD
    preferred_tech:
        - Java
        - Ruby
    work_arrangement:
        - remote
        - hybrid
        - onsite
