package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"linkedin-jobs/internal/config"
	"linkedin-jobs/internal/profile"
	"linkedin-jobs/internal/render"
)

var profileCmd = &cobra.Command{
	Use:   "profile",
	Short: "Show your preference knobs (drive fit scoring & hard filtering)",
	Long: `Your candidate context lives in settings.yaml under the ` + "`profile:`" + `
section (resolved at ~/.linkedin-jobs/settings.yaml, or $LJ_SETTINGS_FILE).

The structured knobs (work_arrangement, min_salary, preferred_tech,
avoided_tech) drive the system rubrics. Location is scored as a dynamic
rubric generated by ` + "`setup`" + ` from your preferences paragraph. Edit
settings.yaml by hand to tune the structured knobs, or run

    linkedin-jobs profile show`,
}

var profileShowCmd = &cobra.Command{
	Use:   "show",
	Short: "Show the active preference knobs",
	RunE: func(cmd *cobra.Command, args []string) error {
		settings, _ := config.LoadSettings()
		p, err := profile.Load(settings.Profile)
		if err != nil {
			die("failed to read profile: %v", err)
		}
		if jsonOut {
			render.AsJSON(os.Stdout, p)
			return nil
		}
		fmt.Printf("Preference knobs (%s → profile:):\n", config.SettingsPath())
		fmt.Printf("  work arrangement: %s\n", orNoneSlice(p.PrefWorkArrangement))
		if p.PrefMinSalary != nil {
			fmt.Printf("  min salary:        %s%.0f %s\n", currencyLabel(p.PrefMinSalaryCurrency), *p.PrefMinSalary, orNoneCurrency(p.PrefMinSalaryCurrency))
		} else {
			fmt.Println("  min salary:        (none)")
		}
		if len(p.PrefPreferredTech) > 0 {
			fmt.Printf("  preferred tech:    %d — %s\n", len(p.PrefPreferredTech), strings.Join(p.PrefPreferredTech, ", "))
		} else {
			fmt.Println("  preferred tech:    (none)")
		}
		if len(p.PrefAvoidedTech) > 0 {
			fmt.Printf("  avoided tech:      %d — %s\n", len(p.PrefAvoidedTech), strings.Join(p.PrefAvoidedTech, ", "))
		} else {
			fmt.Println("  avoided tech:      (none)")
		}
		if p.UpdatedAt != "" {
			fmt.Printf("\nLoaded at: %s\n", p.UpdatedAt)
		}
		return nil
	},
}

func orNoneSlice(ss []string) string {
	if len(ss) == 0 {
		return "(none)"
	}
	return strings.Join(ss, ", ")
}

// orNoneCurrency hides an empty currency code in display when salary is set.
func orNoneCurrency(code string) string {
	if code == "" {
		return "(raw compare)"
	}
	return code
}

// currencyLabel renders a currency code as a leading symbol for display, e.g.
// "CAD" -> "CA$" , "USD" or "" -> "$".
func currencyLabel(code string) string {
	switch strings.ToUpper(strings.TrimSpace(code)) {
	case "CAD":
		return "CA$"
	case "USD", "":
		return "$"
	case "EUR":
		return "€"
	case "GBP":
		return "£"
	}
	return strings.ToUpper(strings.TrimSpace(code)) + " "
}

func init() {
	profileCmd.AddCommand(profileShowCmd)
	rootCmd.AddCommand(profileCmd)
}
