package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// settingsFile points LoadSettings at an isolated temp path for the duration of
// the test (so the real settings.yaml in the repo root is never read). The path
// need not exist — a missing file yields defaults.
func settingsFile(t *testing.T) string {
	t.Helper()
	return filepath.Join(t.TempDir(), "settings.yaml")
}

func TestLoadSettings_DefaultWhenAbsent(t *testing.T) {
	t.Setenv("LJ_SETTINGS_FILE", settingsFile(t))
	s, err := LoadSettings()
	if err != nil {
		t.Fatalf("LoadSettings: %v", err)
	}
	// Two system rubrics by default (salary, work_arrangement). Location is now
	// a dynamic rubric generated by setup.
	if n := len(s.Scoring.Rubrics); n != 2 {
		t.Fatalf("default rubrics = %d, want 2", n)
	}
	for _, r := range s.Scoring.Rubrics {
		if r.Kind != "system" {
			t.Errorf("default rubric %q kind = %q, want system", r.ID, r.Kind)
		}
		if r.Weight != 5 {
			t.Errorf("default rubric %q weight = %d, want 5", r.ID, r.Weight)
		}
	}
}

func TestLoadSettings_RubricsFromFile(t *testing.T) {
	p := settingsFile(t)
	os.WriteFile(p, []byte("scoring:\n  rubrics:\n    - id: salary\n      kind: system\n      weight: 8\n    - id: free_snacks\n      kind: dynamic\n      weight: 99\n"), 0o644)
	t.Setenv("LJ_SETTINGS_FILE", p)
	s, err := LoadSettings()
	if err != nil {
		t.Fatalf("LoadSettings: %v", err)
	}
	if len(s.Scoring.Rubrics) != 2 {
		t.Fatalf("rubrics = %d, want 2", len(s.Scoring.Rubrics))
	}
	if s.Scoring.Rubrics[0].Weight != 8 {
		t.Errorf("salary weight = %d, want 8", s.Scoring.Rubrics[0].Weight)
	}
	// Out-of-range weight (99) clamped to 5.
	if s.Scoring.Rubrics[1].Weight != 5 {
		t.Errorf("free_snacks weight = %d, want 5 (clamped)", s.Scoring.Rubrics[1].Weight)
	}
}

// TestSave_StripObsoleteKeys verifies that SaveProfile/SaveRubrics drop the
// filter.auto_filter / enrich.* / scoring.reason_threshold keys that older
// binaries wrote. Without stripping, the generic-map round-trip would keep
// these dead knobs alive forever.
func TestSave_StripObsoleteKeys(t *testing.T) {
	p := settingsFile(t)
	t.Setenv("LJ_SETTINGS_FILE", p)
	seed := []byte("filter:\n  auto_filter: true\nenrich:\n  auto_enrich_on_save: false\nscoring:\n  reason_threshold: 70\n  rubrics:\n    - id: salary\n      kind: system\n      weight: 5\nprofile:\n  min_salary: 200000\n")
	if err := os.WriteFile(p, seed, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := SaveProfile(ProfileSettings{MinSalary: ptrFloat(150000)}); err != nil {
		t.Fatalf("SaveProfile: %v", err)
	}
	if err := SaveRubrics(DefaultScoringSettings().Rubrics); err != nil {
		t.Fatalf("SaveRubrics: %v", err)
	}

	got, _ := os.ReadFile(p)
	gotStr := string(got)
	for _, bad := range []string{"auto_filter", "auto_enrich_on_save", "reason_threshold", "filter:", "enrich:"} {
		if strings.Contains(gotStr, bad) {
			t.Errorf("saved settings still contains obsolete token %q\n%s", bad, gotStr)
		}
	}
}

func ptrFloat(v float64) *float64 { return &v }

// TestLoadSettings_AlwaysDefaultsSalaryFields confirms the salary-floor pair
// is always populated after load, even when settings.yaml omits them entirely.
// min_salary defaults to 0 (no floor), min_salary_currency defaults to USD.
// This is the load-time mirror of the "always present in settings.yaml" rule
// enforced by the omitempty removal on those two struct tags.
func TestLoadSettings_AlwaysDefaultsSalaryFields(t *testing.T) {
	p := settingsFile(t)
	// settings.yaml exists but has NO profile.min_salary or profile.min_salary_currency.
	os.WriteFile(p, []byte("profile:\n  preferred_tech:\n    - Go\n"), 0o644)
	t.Setenv("LJ_SETTINGS_FILE", p)

	s, err := LoadSettings()
	if err != nil {
		t.Fatalf("LoadSettings: %v", err)
	}
	if s.Profile.MinSalary == nil {
		t.Errorf("MinSalary should default to non-nil (0), got nil")
	} else if *s.Profile.MinSalary != 0 {
		t.Errorf("MinSalary default = %.0f, want 0", *s.Profile.MinSalary)
	}
	if s.Profile.MinSalaryCurrency != "USD" {
		t.Errorf("MinSalaryCurrency default = %q, want USD", s.Profile.MinSalaryCurrency)
	}
}

// TestLoadSettings_RejectsUnsupportedCurrency ensures an unknown currency code
// in settings.yaml falls back to USD rather than poisoning the FX layer. This
// guards against user typos and stale LLM output alike.
func TestLoadSettings_RejectsUnsupportedCurrency(t *testing.T) {
	p := settingsFile(t)
	os.WriteFile(p, []byte("profile:\n  min_salary: 100000\n  min_salary_currency: XYZ\n"), 0o644)
	t.Setenv("LJ_SETTINGS_FILE", p)

	s, _ := LoadSettings()
	if s.Profile.MinSalaryCurrency != "USD" {
		t.Errorf("unknown currency should fall back to USD; got %q", s.Profile.MinSalaryCurrency)
	}
}

// TestSaveProfile_AlwaysWritesSalaryFields confirms SaveProfile round-trips
// min_salary and min_salary_currency unconditionally — they never get dropped
// by omitempty. A re-load after a save of zero-value profile must still see
// min_salary: 0 and min_salary_currency: USD.
func TestSaveProfile_AlwaysWritesSalaryFields(t *testing.T) {
	p := settingsFile(t)
	t.Setenv("LJ_SETTINGS_FILE", p)

	// Save a profile with a deliberately empty salary floor.
	if err := SaveProfile(ProfileSettings{}); err != nil {
		t.Fatalf("SaveProfile: %v", err)
	}
	raw, _ := os.ReadFile(p)
	rawStr := string(raw)
	if !strings.Contains(rawStr, "min_salary:") {
		t.Errorf("saved YAML missing 'min_salary:'\n%s", rawStr)
	}
	if !strings.Contains(rawStr, "min_salary_currency:") {
		t.Errorf("saved YAML missing 'min_salary_currency:'\n%s", rawStr)
	}

	// And the round-trip load should see the defaults.
	s, _ := LoadSettings()
	if s.Profile.MinSalary == nil || *s.Profile.MinSalary != 0 {
		t.Errorf("round-trip MinSalary = %v, want 0", s.Profile.MinSalary)
	}
	if s.Profile.MinSalaryCurrency != "USD" {
		t.Errorf("round-trip MinSalaryCurrency = %q, want USD", s.Profile.MinSalaryCurrency)
	}
}
