package config

import (
	"os"
	"path/filepath"
	"testing"
)

// settingsFile points LoadSettings at an isolated temp path for the duration of
// the test (so the real settings.yaml in the repo root is never read). The path
// need not exist — a missing file yields defaults.
func settingsFile(t *testing.T) string {
	t.Helper()
	return filepath.Join(t.TempDir(), "settings.yaml")
}

func TestLoadSettings_DefaultWhenAbsent(t *testing.T) {
	t.Setenv("LJ_SETTINGS_FILE", settingsFile(t))
	s, err := LoadSettings()
	if err != nil {
		t.Fatalf("LoadSettings: %v", err)
	}
	// Two system rubrics by default (salary, work_arrangement). Location is now
	// a dynamic rubric generated by setup.
	if n := len(s.Scoring.Rubrics); n != 2 {
		t.Fatalf("default rubrics = %d, want 2", n)
	}
	for _, r := range s.Scoring.Rubrics {
		if r.Kind != "system" {
			t.Errorf("default rubric %q kind = %q, want system", r.ID, r.Kind)
		}
		if r.Weight != 5 {
			t.Errorf("default rubric %q weight = %d, want 5", r.ID, r.Weight)
		}
	}
}

func TestLoadSettings_RubricsFromFile(t *testing.T) {
	p := settingsFile(t)
	os.WriteFile(p, []byte("scoring:\n  rubrics:\n    - id: salary\n      kind: system\n      weight: 8\n    - id: free_snacks\n      kind: dynamic\n      weight: 99\n"), 0o644)
	t.Setenv("LJ_SETTINGS_FILE", p)
	s, err := LoadSettings()
	if err != nil {
		t.Fatalf("LoadSettings: %v", err)
	}
	if len(s.Scoring.Rubrics) != 2 {
		t.Fatalf("rubrics = %d, want 2", len(s.Scoring.Rubrics))
	}
	if s.Scoring.Rubrics[0].Weight != 8 {
		t.Errorf("salary weight = %d, want 8", s.Scoring.Rubrics[0].Weight)
	}
	// Out-of-range weight (99) clamped to 5.
	if s.Scoring.Rubrics[1].Weight != 5 {
		t.Errorf("free_snacks weight = %d, want 5 (clamped)", s.Scoring.Rubrics[1].Weight)
	}
}
